Ticket/urls.py
from django.urls import path, include
from .views import TicketDeleteView, all_tickets, delete_comment, open_tickets, create_ticket, dashboard, TicketDetailView, update_ticket

urlpatterns = [
    path('', dashboard, name='Dashboard'),
    path('detail-ticket/<int:pk>', TicketDetailView.as_view(), name='detail-ticket'),
    path('create-ticket/', create_ticket, name='create-ticket'),
    path('update-ticket/<int:pk>', update_ticket, name='update-ticket'),
    path('<int:pk>/delete-ticket/', TicketDeleteView.as_view(), name='delete-ticket'),
    path('all-tickets/', all_tickets, name='all-tickets'),
    path('open-tickets/', open_tickets, name='open-tickets'),
    path('detail-ticket/<int:pk>/delete-comment/<int:id>', delete_comment, name='delete-comment'),
]

supportticket/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import loginView, logoutView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', loginView, name='login'),
    path('logout/', logoutView, name='logout'),
    path('Dashboard/', include('Ticket.urls')),
    path('members/', include('members.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ticket/models.py
from django.db import models
from django.contrib.auth.models import User
from .validators import validate_file_size, validate_file_extension, validate_file_extension1

# Create your models here.
class Ticket(models.Model):
    Customer = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    Subject = models.CharField(max_length=100, help_text='The subject of your problem or question')
    Description = models.CharField(max_length=1000, help_text='Describe your problem here!')
    Up_File = models.FileField(upload_to='dokumen/', verbose_name="", validators=[validate_file_size,validate_file_extension1], null=True, blank=True, help_text='This field is not required')
    Created_at = models.DateTimeField(auto_now_add=True)
    Last_update = models.DateTimeField(auto_now=True)
    
    STATUS = (
        ('Open', 'Open'),
        ('Close', 'Close'),
    )
    Status = models.CharField(max_length=10, choices=STATUS, default='Open', blank=True, null=True)

    LEVEL = (
        ('Low', 'Low'),
        ('Moderate', 'Moderate'),
        ('High', 'High'),
    )
    Level = models.CharField(max_length=10, choices=LEVEL, default='Low', help_text='Question Difficulty Level')

    def __str__(self):
        return str(self.Customer) + ' | ' + self.Subject

class TicketComment(models.Model):
    ticket = models.ForeignKey(Ticket, related_name="comments", on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    admin = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.CharField(max_length=1000)
    Up_Doc = models.FileField(upload_to='dokumen/comment/', verbose_name="", validators=[validate_file_size,validate_file_extension], null=True, blank=True)

    def _str_(self):
        return str(self.ticket) + ' | ' + self.comment + ' | ' + str(self.admin)

Ticket/forms.py
from django import forms
from .models import Ticket, TicketComment
from django.contrib.auth.models import User

class DateInput(forms.DateInput):
    input_type = 'date'
    
    
class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = '__all__'
        labels = {
            'Customer' : 'Creator',
            'Up_File':'Upload File (PDF, JPEG, JPG, and PNG format. Max. Size: 1MB)'
        }
        widgets = {
            'Customer' : forms.Select(attrs={'class': 'form-control','readonly':'readonly',}),
            'Subject' : forms.TextInput(attrs={'class': 'form-control col-md-7'}),
            'Description' : forms.Textarea(attrs={'class': 'form-control col-md-8','rows':'6'}),
            'Status' : forms.Select(attrs={'class': 'form-control col-md-3'}),
            'Level' : forms.Select(attrs={'class': 'form-control col-md-3'}),
        }


class TicketCommentForm(forms.ModelForm):
    class Meta:
        model = TicketComment
        fields = ('comment', 'Up_Doc',)
        labels = {
            'comment' : 'Comment/Response', 'Up_Doc':'Upload File (PDF, JPEG, JPG, and PNG format. Max. Size: 1MB)'
        }
        widgets = {
            'Up_Doc' : forms.FileInput(attrs={'class': 'form-control-file'}),
            'comment' : forms.Textarea(attrs={'class': 'md-textarea form-control', 'placeholder':'Response here ...', 'rows':'4'}),
        }

Ticket/views.py
from django.shortcuts import get_object_or_404, render, redirect, reverse
from .models import Ticket, TicketComment
from .forms import TicketForm, TicketCommentForm
from django.views.generic import DetailView
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.views.generic import DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

def open_tickets(request):
    page = request.GET.get('page')
    t_open = Ticket.objects.filter(Status='Open').count()
    all_t = Ticket.objects.all().count()
    t_count = Ticket.objects.filter(Customer=request.user).count()
    open_tickets = Ticket.objects.filter(Status='Open').order_by('-Created_at')
    paginator = Paginator(open_tickets, 5)
    open_tickets = paginator.get_page(page)
    nums = "a" * open_tickets.paginator.num_pages
    context = {
        'title':'Open Tickets',
        'open_tickets':open_tickets,
        'nums':nums,
        't_open':t_open,
        'all_t':all_t,
        't_count':t_count
    }
    return render(request, 'active_tickets.html', context)


def all_tickets(request):
    if 'search' in request.GET and request.GET['search']:
        page = request.GET.get('page', 1)
        search_t = request.GET['search']
        all_tickets = Ticket.objects.filter(Q(Subject__icontains=search_t) | Q(Customer__first_name__icontains=search_t) | Q(Customer__last_name__icontains=search_t) | Q(Customer__username__icontains=search_t) | Q(Status__icontains=search_t) | Q(Level__icontains=search_t)).order_by('-Created_at').distinct()
        paginator = Paginator(all_tickets, 10)
        all_tickets = paginator.get_page(page)
        nums = "a" * all_tickets.paginator.num_pages
        t_count = Ticket.objects.filter(Customer=request.user).count()
        t_open = Ticket.objects.filter(Status='Open').count()
        all_t = Ticket.objects.all().count()
        context = {
            'title':'All Tickets',
            'all_tickets':all_tickets,
            'nums':nums,
            'search_t':search_t,
            't_count':t_count,
            't_open':t_open,
            'all_t':all_t
        }
        return render (request, 'all_tickets.html', context)
    else:
        page = request.GET.get('page')
        all_tickets = Ticket.objects.all().order_by('-Created_at')
        all_t = Ticket.objects.all().count()
        paginator = Paginator(all_tickets, 10)
        all_tickets = paginator.get_page(page)
        nums = "a" * all_tickets.paginator.num_pages
        t_count = Ticket.objects.filter(Customer=request.user).count()
        t_open = Ticket.objects.filter(Status='Open').count()
        context = {
            'title':'All Tickets',
            'all_tickets':all_tickets,
            'nums':nums,
            'all_t':all_t,
            't_count':t_count,
            't_open':t_open,
        }
        return render (request, 'all_tickets.html', context)


class TicketDeleteView(LoginRequiredMixin, DeleteView):
    model = Ticket
    template_name = 'delete_ticket.html'
    success_url = '/'
    success_message = "Ticket Deleted Successfully"

    def get(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(TicketDeleteView, self).delete(request, *args, **kwargs)

def delete_comment(request, pk, id):
    comment = get_object_or_404(TicketComment, id=id)
    comment.delete()
    messages.info(request, "Comment Deleted Successfully")
    return redirect('detail-ticket', pk=pk)

@login_required(login_url='login')
def create_ticket(request):
    form = TicketForm()
    context = {
        'title' : 'Create Ticket',
        'form' : form,
    }

    if request.method == "POST":
        if request.user.is_authenticated:
            form = TicketForm(request.POST, request.FILES or None)

            for field in form:
                print(field.value())

            if form.is_valid():
                obj = form.save(commit=False)
                obj.Customer = User.objects.get(pk=request.user.id)
                obj.save()
                messages.success(request, "Ticket Created Successfully")
                return redirect('Dashboard')
            else:
                print(form.errors)
                messages.warning(request, (form.errors))
                return redirect('create-ticket')
        else:
            form = TicketForm()
        return render(request, 'create-ticket.html', {'form':form,'title':'Create Ticket'})
    return render(request, 'create_ticket.html', context)

@login_required(login_url='login')
def dashboard(request):
    page = request.GET.get('page')
    my_ticket = Ticket.objects.filter(Customer=request.user).order_by('-Created_at')
    paginator = Paginator(my_ticket, 5)
    my_ticket = paginator.get_page(page)
    nums = "a" * my_ticket.paginator.num_pages
    t_count = Ticket.objects.filter(Customer=request.user).count()
    t_open = Ticket.objects.filter(Status='Open').count()
    all_t = Ticket.objects.all().count()

    context = {
        'title' : 'Dashboard',
        'my_ticket' : my_ticket,
        't_count' : t_count,
        't_open' : t_open,
        'all_t' : all_t,
        'nums' : nums,
    }
    template_name : None    
    if request.user.is_authenticated:
        template_name = 'dashboard.html'
    else:
        template_name = 'login.html'
    return render(request, template_name, context)


class TicketDetailView(DetailView):
    model = Ticket
    template_name = 'detail_ticket.html'
    extra_context = {'title':'Ticket Details'}
    slug_field = "slug"
    count_hit = True

    form = TicketCommentForm

    def post(self, request, *args, **kwargs):
        form = TicketCommentForm(request.POST, request.FILES or None)
        if form.is_valid():
            ticket = self.get_object()
            form.instance.admin = request.user
            form.instance.ticket = ticket
            form.save()
            messages.success(request, "Comment Added Successfully")

            return redirect(reverse("detail-ticket", kwargs={'pk': ticket.id}))
        else:
            ticket = self.get_object()
            messages.warning(request, (form.errors))
            return redirect(reverse("detail-ticket", kwargs={'pk': ticket.id}))

    def get_context_data(self, **kwargs):
        ticket_comments_count = TicketComment.objects.all().filter(ticket=self.object.id).count()
        ticket_comments = TicketComment.objects.all().filter(ticket=self.object.id)
        context = super().get_context_data(**kwargs)
        context.update({
            'form': self.form,
            'ticket_comments': ticket_comments,
            'ticket_comments_count': ticket_comments_count,
        })
        return context
    
    def get_absolute_url(self):
        return reverse('detail-ticket', kwargs={'pk': self.pk})




def update_ticket(request, pk):
    ticket = Ticket.objects.get(pk=pk)
    form = TicketForm(instance=ticket)

    if request.method == "POST":
        if request.user.is_authenticated:
            form = TicketForm(request.POST, request.FILES, instance=ticket)

            for field in form:
                print(field.value())

            if form.is_valid():
                form.save()
                messages.success(request, "Ticket Updated Successfully")
                return redirect('Dashboard')
            else:
                print(form.errors)
                messages.warning(request, (form.errors))
                return redirect('update-ticket', pk)
    context = {
        'title':'Update Ticket',
        'form':form,
    }
    return render(request, 'update_ticket.html',context)

    #def get_context_data(self, **kwargs):
        #context = super().get_context_data(**kwargs)
        #context['form'] = self.get_form()
        #return 
    
    #def form_valid(self, form):
        #new_comment = form.save(commit=False)
        #new_comment.ticket = self.get_object()
        #return super(TicketDetailView, self).form_valid(form)

Ticket/templates/active_tickets.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% if messages %} {% for message in messages %}
<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div> {% endfor %} {% endif %}
{% include 'topside.html' %}
<link rel="stylesheet" href="{% static 'css/details.css' %}">
<br>
<hr>
{% if t_open >= 1 %}
<center><h2>Active Tickets</h2></center>
<hr>
<br><br>
<div class="table-responsive">
<table class="table table-bordered">
    <thead class="thead-dark">
      <tr>
        <th style="text-align: center;" scope="col">Tickets</th>
        <th scope="col">Details</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    {% for T in open_tickets %}
    <tbody>
      <tr>
        <th style="text-align: center;" scope="row">{{T.id}}</th>
        <td><a href="{% url 'detail-ticket' T.pk %}">{{T.Subject}}</a><br>{{T.Customer.get_full_name}}
            <br>{{T.Created_at | date:"l, d F Y H:i:s"}}    
        <br><span>{{T.Status}}</span>&nbsp;<span>{{T.Level}}</span>
        {% if request.user.is_superuser and request.user == T.Customer %}
        <td><a class="btn btn-primary btn-sm" href="{% url 'update-ticket' T.pk %}">Update</a>
          <a class="btn btn-danger btn-sm delete-ticket" href="{% url 'delete-ticket' T.pk %}">Delete</a>
        </td>
        {% elif request.user.is_superuser %}
        <td>
          <a class="btn btn-danger btn-sm delete-ticket" href="{% url 'delete-ticket' T.pk %}">Delete</a></td>
        {% elif request.user == T.Customer %}
        <td><a class="btn btn-primary btn-sm" href="{% url 'update-ticket' T.pk %}">Update</a></td>
        {% endif %}
      </tr>
    </tbody>
    {% endfor %}
  </table>
</div>
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% if open_tickets.has_previous %}
        <li class="page-item"><a class="page-link" href="{% if search_t %}?search={{ search_t }}&page=1{% else %}?page=1{% endif %}">&laquo First</a></li>
        <li class="page-item"><a class="page-link" href="{% if search_t %}?search={{ search_t }}&page={{open_tickets.previous_page_number}}{% else %}?page={{open_tickets.previous_page_number}}{% endif %}">Previous</a></li>
        {% endif %}
        <!-- <li class="page-item disabled"><a href="#" class="page-link"> Page {{open_tickets.number}} of {{open_tickets.paginator.num_pages}}</a></li> -->
        {% for i in nums %}
        <li class="page-item"><a class="page-link" href="{% if search_t %}?search={{ search_t }}&page={{forloop.counter}}{% else %}?page={{forloop.counter}}{% endif %}">{{ forloop.counter }}</a></li>
        {% endfor %} {% if open_tickets.has_next %}
        <li class="page-item"><a class="page-link" href="{% if search_t %}?search={{ search_t }}&page={{open_tickets.next_page_number}}{% else %}?page={{open_tickets.next_page_number}}{% endif %}">Next</a></li>
        <li class="page-item"><a class="page-link" href="{% if search_t %}?search={{ search_t }}&page={{open_tickets.paginator.num_pages}}{% else %}?page={{open_tickets.paginator.num_pages}}{% endif %}">Last &raquo</a></li> {% endif %}
    </ul>
</nav>
<br><br>
{% else %}
    <center><h2>No one has made a ticket yet</h2></center>
    <a href="{% url 'create-ticket' %}"><button class="btn btn-success btn-sm" style="margin-top: 20px;">Create Ticket</button></a>
{% endif %}
<script type="text/javascript" src="{% static 'js/span.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">
  $(document).on('click', '.delete-ticket', function(){
    return confirm('Are you sure you want to delete this?');
})
</script>
{% endblock %}1

Ticket/templates/all_tickets.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% if messages %} {% for message in messages %}
<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div> {% endfor %} {% endif %}
{% include 'topside.html' %}
<link rel="stylesheet" href="{% static 'css/details.css' %}">
<br>
<hr>
{% if all_t >= 1 %}
<center><h2>All Tickets</h2></center>
<hr>
<form class="form-inline my-2 my-lg-0" action="{% url 'all-tickets' %}" style="float: right;">
  <div class="input-group me-2">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
      <button class="btn btn-outline-primary" type="submit">Search</button>
  </div>
</form><br><br>
<div class="table-responsive">
<table class="table table-bordered">
    <thead class="thead-dark">
      <tr>
        <th style="text-align: center;" scope="col">Tickets</th>
        <th scope="col">Details</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    {% for T in all_tickets %}
    <tbody>
      <tr>
        <th style="text-align: center;" scope="row">{{T.id}}</th>
        <td><a href="{% url 'detail-ticket' T.pk %}">{{T.Subject}}</a><br>{{T.Customer.get_full_name}}
            <br>{{T.Created_at | date:"l, d F Y H:i:s"}}    
        <br><span>{{T.Status}}</span>&nbsp;<span>{{T.Level}}</span>
        </td>
        {% if request.user.is_superuser and request.user == T.Customer %}
        <td><a class="btn btn-primary btn-sm" href="{% url 'update-ticket' T.pk %}">Update</a>
          <a class="btn btn-danger btn-sm delete-ticket" href="{% url 'delete-ticket' T.pk %}">Delete</a>
        </td>
        {% elif request.user.is_superuser %}
        <td>
          <a class="btn btn-danger btn-sm delete-ticket" href="{% url 'delete-ticket' T.pk %}">Delete</a></td>
        {% elif request.user == T.Customer %}
        <td><a class="btn btn-primary btn-sm" href="{% url 'update-ticket' T.pk %}">Update</a></td>
        {% endif %}
      </tr>
    </tbody>
    {% endfor %}
  </table>
</div>
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% if all_tickets.has_previous %}
        <li class="page-item"><a class="page-link" href="{% if search_t %}?search={{ search_t }}&page=1{% else %}?page=1{% endif %}">&laquo First</a></li>
        <li class="page-item"><a class="page-link" href="{% if search_t %}?search={{ search_t }}&page={{all_tickets.previous_page_number}}{% else %}?page={{all_tickets.previous_page_number}}{% endif %}">Previous</a></li>
        {% endif %}
        <!-- <li class="page-item disabled"><a href="#" class="page-link"> Page {{all_tickets.number}} of {{all_tickets.paginator.num_pages}}</a></li> -->
        {% for i in nums %}
        <li class="page-item"><a class="page-link" href="{% if search_t %}?search={{ search_t }}&page={{forloop.counter}}{% else %}?page={{forloop.counter}}{% endif %}">{{ forloop.counter }}</a></li>
        {% endfor %} {% if all_tickets.has_next %}
        <li class="page-item"><a class="page-link" href="{% if search_t %}?search={{ search_t }}&page={{all_tickets.next_page_number}}{% else %}?page={{all_tickets.next_page_number}}{% endif %}">Next</a></li>
        <li class="page-item"><a class="page-link" href="{% if search_t %}?search={{ search_t }}&page={{all_tickets.paginator.num_pages}}{% else %}?page={{all_tickets.paginator.num_pages}}{% endif %}">Last &raquo</a></li> {% endif %}
    </ul>
</nav>
<br><br>
{% else %}
    <center><h2>No one has made a ticket yet</h2></center>
    <a href="{% url 'create-ticket' %}"><button class="btn btn-success btn-sm" style="margin-top: 20px;">Create Ticket</button></a>
{% endif %}
<script type="text/javascript" src="{% static 'js/span.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">
  $(document).on('click', '.delete-ticket', function(){
    return confirm('Are you sure you want to delete this?');
})
</script>
{% endblock %}1

Ticket/templates/create_ticket.html
{% extends 'base.html' %}
{% block content %}
{% load custom_tags %}
<br>
{% if messages %} {% for message in messages %}
        <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div> {% endfor %} {% endif %}
<hr>
<center><h3>New Ticket</h3></center>
<hr>
<div class="alert alert-info">
    <p><strong>Info!</strong> Please fill in the details of the ticket.</p>
</div>
<br>
<div style="margin: 0x auto 20px 0px;">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{form.Subject | append_ast_if_req }}{{form.Subject}}{{form.Subject.help_text}}<br>
            <br>
            {{form.Description | append_ast_if_req}}{{form.Description}}{{form.Description.help_text}}<br>
            <br>
            {{form.Up_File | append_ast_if_req}}<br>{{form.Up_File}}<br>({{form.Up_File.help_text}})
            <br>
            <br>
            {{form.Level | append_ast_if_req}}{{form.Level}}{{form.Level.help_text}}
        </div>
        <center><button class="btn btn-success btn-md" type="Submit">Create Ticket</button></center>
    </form>
    <a href="{{request.META.HTTP_REFERER | escape}}"><button class="btn btn-danger btn-sm" style="margin-top: 20px;">Back</button></a>
</div>
<br>
<br><br>
{% endblock %}

Ticket/templates/dashboard.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% if messages %} {% for message in messages %}
<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div> {% endfor %} {% endif %}
{% include 'topside.html' %}
<link rel="stylesheet" href="{% static 'css/details.css' %}">
<br>
<hr>
{% if t_count >= 1 %}
<center><h2>My Tickets</h2></center>
<hr>
<a href="{% url 'create-ticket' %}"><button class="btn btn-success btn-sm" style="margin-top: 20px;">Create Ticket</button></a>
<br><br>
<div class="table-responsive">
<table class="table table-bordered">
    <thead class="thead-dark">
      <tr>
        <th style="text-align: center;" scope="col">Tickets</th>
        <th scope="col">Details</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    {% for T in my_ticket %}
    <tbody>
      <tr>
        <th style="text-align: center;" scope="row">{{T.id}}</th>
        <td><a href="{% url 'detail-ticket' T.pk %}">{{T.Subject}}</a><br>{{T.Customer.get_full_name}}
            <br>{{T.Created_at | date:"l, d F Y H:i:s"}}    
        <br><span>{{T.Status}}</span>&nbsp;<span>{{T.Level}}</span>
        </td>
        <td><a class="btn btn-primary btn-sm" href="{% url 'update-ticket' T.pk %}">Update</a>
        {% if request.user.is_superuser %}
        <a class="btn btn-danger btn-sm delete-ticket" href="{% url 'delete-ticket' T.pk %}">Delete</a>
        {% else %}

        {% endif %}
        </td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
</div>
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% if my_ticket.has_previous %}
        <li class="page-item"><a class="page-link" href="{% if search_t %}?search={{ search_t }}&page=1{% else %}?page=1{% endif %}">&laquo First</a></li>
        <li class="page-item"><a class="page-link" href="{% if search_t %}?search={{ search_t }}&page={{my_ticket.previous_page_number}}{% else %}?page={{my_ticket.previous_page_number}}{% endif %}">Previous</a></li>
        {% endif %}
        <!-- <li class="page-item disabled"><a href="#" class="page-link"> Page {{my_ticket.number}} of {{my_ticket.paginator.num_pages}}</a></li> -->
        {% for i in nums %}
        <li class="page-item"><a class="page-link" href="{% if search_t %}?search={{ search_t }}&page={{forloop.counter}}{% else %}?page={{forloop.counter}}{% endif %}">{{ forloop.counter }}</a></li>
        {% endfor %} {% if my_ticket.has_next %}
        <li class="page-item"><a class="page-link" href="{% if search_t %}?search={{ search_t }}&page={{my_ticket.next_page_number}}{% else %}?page={{my_ticket.next_page_number}}{% endif %}">Next</a></li>
        <li class="page-item"><a class="page-link" href="{% if search_t %}?search={{ search_t }}&page={{my_ticket.paginator.num_pages}}{% else %}?page={{my_ticket.paginator.num_pages}}{% endif %}">Last &raquo</a></li> {% endif %}
    </ul>
</nav>
<br><br>
{% else %}
    <center><h2>You haven't made a ticket yet</h2></center>
    <center><a href="{% url 'create-ticket' %}"><button class="btn btn-success btn-sm" style="margin-top: 20px;">Create Ticket</button></a></center>
    <br><br><br>
{% endif %}
<script type="text/javascript" src="{% static 'js/span.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">
  $(document).on('click', '.delete-ticket', function(){
    return confirm('Are you sure you want to delete this?');
})
</script>
{% endblock %}1

Ticket/templates/update_ticket.html
{% extends 'base.html' %}
{% block content %}
{% load custom_tags %}
<br>
{% if messages %} {% for message in messages %}
        <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div> {% endfor %} {% endif %}
<hr>
<center><h3>Update Ticket</h3></center>
<hr>
<br>
<div style="margin: 0x auto 20px 0px;">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{form.Customer.label_tag}}{{form.Customer}}
            <br>
            {{form.Subject | append_ast_if_req}}{{form.Subject}}
            <br>
            {{form.Description | append_ast_if_req}}{{form.Description}}
            <br>
            {{form.Up_File.label_tag}}<br>{{form.Up_File}}
            <br>
            <br>
            {{form.Level | append_ast_if_req}}{{form.Level}}
            <br>
            {{form.Status.label_tag}}{{form.Status}}
        </div>
        <center><button class="btn btn-success btn-md" type="Submit">Update Ticket</button></center>
    </form>
    <a href="{{request.META.HTTP_REFERER | escape}}"><button class="btn btn-danger btn-sm" style="margin-top: 20px;">Back</button></a>
</div>
<br><br>
<span>Note: * is required</span>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script type="text/javascript">
    $('#id_Customer').css('pointer-events', 'none').on('focus', function() {
        $(this).blur();
    });
</script>
{% endblock %}